# OPAL

Opal is [OBiBa](https://www.obiba.org/)’s core database application for biobanks. Participant data, collected by questionnaires, medical instruments, sensors, administrative databases etc. can be integrated and stored in a central data repository under a uniform model. Opal is a web application that can import, process, copy data and has advanced features for cataloging the data (fully described, annotatted and searchable data dictionaries) as recommended by the [Maelstrom Research](https://www.maelstrom-research.org). Opal is typically used in a research center to analyze the data acquired at assessment centres. Its ultimate purpose is to achieve seamless data-sharing among biobanks. Opal is the reference implementation of the [DataSHIELD](http://www.datashield.ac.uk/) infrastructure. More information on Opal can be seen in [Opal description on OBiBa](https://www.obiba.org/pages/products/opal/).

Opal provides the following main features:

- Use of MongoDB, Mysql, MariaDB and/or PostgreSQL as database software backends,
- Import data from various file formats (CSV, SPSS, SAS, Stata etc.) and from SQL databases,
- Export data to various file formats (CSV, SPSS, SAS, Stata etc.) and to SQL databases,
- Plugin architecture to extend import/export capabilities for instance by connecting to data source software such as REDCap, LimeSurvey etc.,
- Store data about any type of "entity", such as subject, sample, geographic area, etc.,
- Store data of any type (e.g., texts, numbers, geo-localisation, images, videos, etc.),
- Import and store genotype data as VCF files (Variant Call format ),
- Reporting using R markdown,
- Data analysis plugins using R,
- ...

Detailed concepts and tutorials for tables can be found here:

- [Variables and Data](http://opaldoc.obiba.org/en/latest/variables-data.html)
- [Identifiers Mappings](http://opaldoc.obiba.org/en/latest/ids.html)
- [Data Harmonization](http://opaldoc.obiba.org/en/latest/data-harmonization.html)

To have a closer look at Opal with table you can try [the demo site](http://opal-demo.obiba.org/) with the credentials:

- username: administrator
- password: password

In this work, we will present the integration of a more flexible data description paradigm called [resources](#resources) that will enable Opal to manage access to Big Data sets and computation units for analysis purpose.

Before introducing this new feature and in order to make the reader familiar with Opal we recommend to visit [the Opal online documentation](http://opaldoc.obiba.org/).
