# Creating DataSHIELD packages

The procedure for the development of a client-side or a server-side package in DataSHIELD is similar as the procedure of creating packages in native R and RStudio. For the devevelopment of a package, the developer will need the R packages [devtools](https://cran.r-project.org/web/packages/devtools/readme/README.html) and [roxygen2](https://cran.r-project.org/web/packages/roxygen2/index.html). Having those packages installed and loaded in the R session, the developer should follow five basic steps:

(1) [Create](https://www.rdocumentation.org/packages/devtools/versions/2.2.2/topics/create) the package directory: this will create the R and the man folders and the DESCRIPTION file in a specified directory. 

(2) Add functions: copy the R scripts of the functions developed in the R folder created at step (1).

(3) Add documentation: add comments at the beginning of each function to give information to the user on what the function does and how the arguments of the function are used. Those comments are compiled into the correct format for the package documentation. More details can be found in the roxygen2 [documentation](https://roxygen2.r-lib.org).

(4) Create the documentation: this automatically adds in the .Rd files to the man directory and a NAMESPACE file to the main package directory. (see the function [document](https://www.rdocumentation.org/packages/devtools/versions/2.3.0/topics/document) in devtools)

(5) [Install](https://www.rdocumentation.org/packages/devtools/versions/2.3.0/topics/install) the development package.

In addition to those steps, the developer can make the package a GitHub repo and allows other developers to commit any further developments and improvements. For more details the reader can have a look on a Git/GitHub [guide](https://kbroman.org/github_tutorial/).

After the development of a client-server pair of DataSHIELD packages the DataSHIELD Development Team can provide a testing framework where the developed functions and packages are tested including tests related to disclosure protection and if all tests are passed, then the package can be become publicly available for use by the DataSHIELD users. Details for the DataSHIELD testing framework can be found in the DataSHIELD [Wiki](https://data2knowledge.atlassian.net/wiki/spaces/DSDEV/pages/658505761/Testing).


